# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\"\x0f\n\rEmptyResponse\"\x0e\n\x0c\x45mptyRequest\"\x1e\n\x0bRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x03\"\x1f\n\x0cRoomResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\x03\"6\n\x14\x41nnounceMafiaRequest\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07room_id\x18\x02 \x01(\x03\",\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\x03\"@\n\rAccuseRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\x03\"\x14\n\x04Role\x12\x0c\n\x04role\x18\x01 \x01(\t\"3\n\x10UsersInfoMessage\x12\r\n\x05names\x18\x01 \x01(\t\x12\x10\n\x08statuses\x18\x02 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\tBoolReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05right\x18\x02 \x01(\x08\x32\x8d\x05\n\x06Server\x12\"\n\x08InitName\x12\x0c.NameRequest\x1a\x06.Reply\"\x00\x12+\n\tGetRoomId\x12\r.EmptyRequest\x1a\r.RoomResponse\"\x00\x12%\n\tGetStream\x12\x0c.RoomRequest\x1a\x06.Reply\"\x00\x30\x01\x12\x35\n\x13StartTheGameRequest\x12\x0c.RoomRequest\x1a\x0e.EmptyResponse\"\x00\x12\'\n\x0eRoleAssignment\x12\x0c.NameRequest\x1a\x05.Role\"\x00\x12.\n\tUsersInfo\x12\x0c.NameRequest\x1a\x11.UsersInfoMessage\"\x00\x12\x30\n\x0cVoteWithChat\x12\x0e.AccuseRequest\x1a\x0e.EmptyResponse\"\x00\x12\x33\n\x0fVoteWithoutChat\x12\x0e.AccuseRequest\x1a\x0e.EmptyResponse\"\x00\x12)\n\x0b\x43heckPerson\x12\x0c.NameRequest\x1a\n.BoolReply\"\x00\x12#\n\tDayResult\x12\x0c.RoomRequest\x1a\x06.Reply\"\x00\x12%\n\x0bNightResult\x12\x0c.RoomRequest\x1a\x06.Reply\"\x00\x12\x37\n\rAnnounceMafia\x12\x15.AnnounceMafiaRequest\x1a\r.EmptyRequest\"\x00\x12\x35\n\x13\x43leanAccusedRequest\x12\x0c.RoomRequest\x1a\x0e.EmptyResponse\"\x00\x12-\n\x0f\x43heckGameEnding\x12\x0c.RoomRequest\x1a\n.BoolReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYRESPONSE._serialized_start=14
  _EMPTYRESPONSE._serialized_end=29
  _EMPTYREQUEST._serialized_start=31
  _EMPTYREQUEST._serialized_end=45
  _ROOMREQUEST._serialized_start=47
  _ROOMREQUEST._serialized_end=77
  _ROOMRESPONSE._serialized_start=79
  _ROOMRESPONSE._serialized_end=110
  _ANNOUNCEMAFIAREQUEST._serialized_start=112
  _ANNOUNCEMAFIAREQUEST._serialized_end=166
  _NAMEREQUEST._serialized_start=168
  _NAMEREQUEST._serialized_end=212
  _ACCUSEREQUEST._serialized_start=214
  _ACCUSEREQUEST._serialized_end=278
  _ROLE._serialized_start=280
  _ROLE._serialized_end=300
  _USERSINFOMESSAGE._serialized_start=302
  _USERSINFOMESSAGE._serialized_end=353
  _REPLY._serialized_start=355
  _REPLY._serialized_end=379
  _BOOLREPLY._serialized_start=381
  _BOOLREPLY._serialized_end=424
  _SERVER._serialized_start=427
  _SERVER._serialized_end=1080
# @@protoc_insertion_point(module_scope)
